import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import Notification from "@/components/Notification";
import HeroNav from "@/components/HeroNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Barn and Blade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <HeroNav />
      <Notification />
      <div className='mt-[6rem]'>
      {children}
      </div>
      <Footer />
    </body>
  </html>
  );
}
